# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
